### ISSUE TITLE
Ticking entity crash - halloween and BoP?

### ISSUE THREAD

**Issue by jc2xs** [KingScar/EOD-Eclipse#2]
Crash report:  https://pastebin.com/yMXJNBLM

Reported to mod author on https://github.com/crazysnailboy/Halloween/issues/3

**Comment by jc2xs** [comment]
Crazysnailboy has released a fix for this one.  And Scar should be able to close this issue on the next pack update.

**Comment by KingScar** [comment]
This has been updated/fixed in alpha 3!

Thanks for reporting!
